// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoIVn5VE7NRRSuAlPF1a6MpzAnxGpXeJg',
    appId: '1:182048701581:android:95430a4fc1fdafea6936c4',
    messagingSenderId: '182048701581',
    projectId: 'flutterchat-e6a21',
    storageBucket: 'flutterchat-e6a21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2g3w6HD0t1qHYx0yVHuCyxd7NjBwdSWY',
    appId: '1:182048701581:ios:2734ffd847fc12506936c4',
    messagingSenderId: '182048701581',
    projectId: 'flutterchat-e6a21',
    storageBucket: 'flutterchat-e6a21.appspot.com',
    androidClientId: '182048701581-s33mg1jo9n1ru9hk23o7ra34vatphhb2.apps.googleusercontent.com',
    iosClientId: '182048701581-p6ga78phee0iaeria687jb0orkhkdeqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );
}
